name: Test
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ] # , macos-latest, windows-latest ]
        go-version: [ '1.17', '1.18', '1.19' ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
      - name: test
        if: success() || failure() # run even if lint or japecheck fails
        uses: n8maninger/action-golang-test@v1
        with:
          args: "-race"
      - name: check endpoints
        if: success() || failure() # run even if lint or test fails
        run: |
          go install go.sia.tech/jape/japecheck@latest
          $(go env GOPATH)/bin/japecheck ./api
