name: Update UI and open PR

on:
  # Run daily
  schedule:
    - cron: '0 0 * * *'
  # Enable manual trigger
  workflow_dispatch:

jobs:
  update-ui:
    runs-on: ubuntu-latest
    steps:
      - name: Update UI and open PR
        uses: SiaFoundation/workflows/.github/actions/ui-update@master
        with:
          moduleName: 'renterd'
          goVersion: '1.21'
          token: ${{ secrets.GITHUB_TOKEN }} 
